public class Employee1 {
     string lastname;
     string firstname;
     decimal exp;
     decimal salary;
       public void setData(string lastname, string firstname,decimal exp,decimal salary)
    {
        system.debug('last name is:'+ lastname);
        system.debug('first name is:'+ firstname);
        system.debug('Experience is:'+ exp);
        system.debug('salary  is:'+ salary);      
}
}