public with sharing class githubex {
    public void method1(){
        System.debug('HI');
    }
    public void method2(){
        System.debug('bye');
    }
    public void method3(){
        System.debug(' hello and bye');
    }
        public void method4(){
        System.debug('hello and bye and welcome to new world');
    }
    public void method5(){
        System.debug('hello and bye and welcome to new world this is method5');
    }
}