public class Student1 {
    public string lastname;
    public double firstname;
     public integer   phone;
    public integer age;
    public void show (string lastname, string firstname,  integer  phone,integer age)
    {
        system.debug( 'student last name is:'+lastname);
        system.debug('student first name is:'+firstname);
        system.debug('student phone number is:'+phone);
        system.debug('student age is:'+age);     
    }  
}