public class Test {        

    public void additionmethod(integer a ,integer b){  
          integer num1 = a;
        integer num2 = b;
        integer res = num1 +num2;
        system.debug('The result is :' + res);
        integer res1 = num1 * num2;
        system.debug('The result is :' + res1);
        integer res2 = num1 - num2;
        system.debug('The result is :' + res2);
        integer res3 = num1 / num2;
        system.debug('The result is :' + res3);
    }
    
}