public with sharing class vscode {
    public  void examplemethod(){
        System.debug('welcome to vs world');
    }
    public  void examplemethod2(){
        System.debug('welcome to vs world and git hub');
    }
        public  void examplemethod3(){
        System.debug('welcome to git hub');
    }
            public  void examplemethod4(){
        System.debug('hello world');
    }
    public  void examplemethod5(){
        System.debug('hello! welcome to developer world');
    }
        public  void examplemethod6(){
        System.debug('addition of two numbers');
    }
    public  void examplemethod7(){
        System.debug('subtraction of two numbers');
    }
    public  void examplemethod8(){
        System.debug('factorial of 5');
    }
    public  void examplemethod9(){
        System.debug('factorial of 10 and last method');
    }



    }