public with sharing class vscode {
    public  void examplemethod(){
        System.debug('welcome to vs world');
    }
    public  void examplemethod2(){
        System.debug('welcome to vs world and git hub');
    }
        public  void examplemethod3(){
        System.debug('welcome to git hub');
    }
            public  void examplemethod4(){
        System.debug('hello world');
    }
    public  void examplemethod5(){
        System.debug('hello! welcome to developer world');
    }
        public  void examplemethod6(){
        System.debug('addition of two numbers');
    }
    public  void examplemethod7(){
        System.debug('subtraction of two numbers');
    }
    public  void examplemethod8(){
        System.debug('factorial of 5');
    }
    public  void examplemethod9(){
        System.debug('factorial of 10 and last method');
    }
     public  void examplemethod10(){
        System.debug('factorial of 20 and last method');
    }
     public  void examplemethod11(){
        System.debug('factorial of 30 and last method');
    }
    public  void examplemethod12(){
        System.debug('factorial of 40 and last method');
    }
    public  void examplemethod13(){
        System.debug('factorial of 50 and last method');
    }
    public  void examplemethod14(){
        System.debug('factorial of 60 and last method');
    }
    public  void examplemethod15(){
        System.debug('factorial of 70 and last method');
    }
    }